language: generic
branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

sudo: required
services:
  - docker

matrix: 
  include:
    - os: linux
    - os: osx

before_install:
- cd releng/config
- openssl aes-256-cbc -K $encrypted_fff3b1abfe83_key -iv $encrypted_fff3b1abfe83_iv
  -in ci.tar.enc -out ci.tar -d
- tar -xf ci.tar
- cd ../..

install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then bash releng/macos/provision.sh; fi

script:
- bash ./releng/ci/travis.sh macos
- bash ./releng/ci/travis.sh ubuntu
- bash ./releng/ci/travis.sh arch
